export const ORDER_REQUESTED = '@@devalpha/ORDER_REQUESTED'
export const ORDER_CREATED = '@@devalpha/ORDER_CREATED'
export const ORDER_PLACED = '@@devalpha/ORDER_PLACED'
export const ORDER_FILLED = '@@devalpha/ORDER_FILLED'
export const ORDER_FAILED = '@@devalpha/ORDER_FAILED'
export const ORDER_REJECTED = '@@devalpha/ORDER_REJECTED'
export const ORDER_CANCELLED = '@@devalpha/ORDER_CANCELLED'
export const ORDER_CANCEL = '@@devalpha/ORDER_CANCEL'
export const INITIALIZED = '@@devalpha/INITIALIZED'
export const FINISHED = '@@devalpha/FINISHED'

export const DASHBOARD_EVENTS = '@@devalpha/DASHBOARD_EVENTS'
export const DASHBOARD_FINISHED = '@@devalpha/DASHBOARD_FINISHED'

export const SOCKET_PORT = '4449'
