export const ORDER_REQUESTED = 'order:requested'
export const ORDER_CREATED = 'order:created'
export const ORDER_PLACED = 'order:placed'
export const ORDER_FILLED = 'order:filled'
export const ORDER_FAILED = 'order:failed'
export const ORDER_REJECTED = 'order:rejected'
export const ORDER_CANCELLED = 'order:cancelled'
export const ORDER_CANCEL = 'order:cancel'
export const INITIALIZED = 'initialized'
export const FINISHED = 'finished'
export const BAR_RECEIVED = 'bar:received'

export const SOCKETIO_CONNECTION = 'connection'
export const SOCKETIO_BACKTESTER_RUN = 'backtester_run'
export const SOCKETIO_BACKTESTER_EVENTS = 'backtester_events'
export const SOCKETIO_BACKTESTER_DONE = 'backtester_done'
