export const ORDER_REQUESTED = '@@vester/ORDER_REQUESTED'
export const ORDER_CREATED = '@@vester/ORDER_CREATED'
export const ORDER_PLACED = '@@vester/ORDER_PLACED'
export const ORDER_FILLED = '@@vester/ORDER_FILLED'
export const ORDER_FAILED = '@@vester/ORDER_FAILED'
export const ORDER_REJECTED = '@@vester/ORDER_REJECTED'
export const ORDER_CANCELLED = '@@vester/ORDER_CANCELLED'
export const ORDER_CANCEL = '@@vester/ORDER_CANCEL'
export const INITIALIZED = '@@vester/INITIALIZED'
export const FINISHED = '@@vester/FINISHED'

export const DASHBOARD_INITIALIZE = '@@vester/DASHBOARD_INITIALIZE'
export const DASHBOARD_EVENTS = '@@vester/DASHBOARD_EVENTS'
export const DASHBOARD_FINISHED = '@@vester/DASHBOARD_FINISHED'

export const SOCKETIO_RECONNECT_FAILED = 'reconnect_failed'
export const SOCKETIO_CONNECT = 'connect'
export const SOCKETIO_CONNECTION = 'connection'
export const SOCKETIO_RECONNECT = 'reconnect'
export const SOCKETIO_DISCONNECT = 'disconnect'
